### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

->
* is_floating_point
* set_printoptions
* numel
* torch.unsqueeze() / torch.squeeze()

In [2]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [3]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *is_floating_point*

In [5]:
# Example 1 - ### 檢查是否為float的形式 ###
a = np.random.rand(1,2,3,3)
print(f'a: {a}')
print(f'float: {torch.is_floating_point(torch.tensor(a))}')

a: [[[[0.41851298 0.08343198 0.46596248]
   [0.87452116 0.27948398 0.81770913]
   [0.38546347 0.86096889 0.39404516]]

  [[0.15365514 0.26366203 0.9238509 ]
   [0.61517688 0.04456527 0.12946831]
   [0.60965313 0.59837361 0.76711803]]]]
float: True


In [7]:
# Example 2 - ### 用 randint讓 type 轉為int ###
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {a}')
print(f'float: {torch.is_floating_point(torch.tensor(a))}')

a: [[2 0]
 [4 2]]
float: False


### Function 2 - set_printoptions

In [17]:
# Example 1 - ### 用 set_printoptions 加入顯示第幾小數點來設定torch顯示的形式 ###
a = np.random.rand(1,2,3,3)
print(f'a: {a}')
torch.set_printoptions(precision=2)
print(f'{torch.tensor(a)}')

a: [[[[0.44770119 0.51822781 0.85435222]
   [0.51209556 0.23600773 0.40953801]
   [0.09872217 0.99602827 0.04723731]]

  [[0.5847554  0.38406126 0.826236  ]
   [0.93881876 0.43435902 0.61713536]
   [0.27454704 0.91902008 0.410688  ]]]]
tensor([[[[0.45, 0.52, 0.85],
          [0.51, 0.24, 0.41],
          [0.10, 1.00, 0.05]],

         [[0.58, 0.38, 0.83],
          [0.94, 0.43, 0.62],
          [0.27, 0.92, 0.41]]]],
       dtype=torch.float64)


In [21]:
# Example 2 - ### 用 set_printoptions 使用其他參數來設定torch顯示的形式 ###
torch.set_printoptions(precision=2, edgeitems=4, linewidth=32)
print(f'{torch.tensor(a)}')

tensor([[[[0.45, 0.52, 0.85],
          [0.51, 0.24, 0.41],
          [0.10, 1.00, 0.05]],

         [[0.58, 0.38, 0.83],
          [0.94, 0.43, 0.62],
          [0.27, 0.92, 0.41]]]],
       dtype=torch.float64)


### Function 3 - numel

In [5]:
# Example 1 - ### 返回有幾個元素 ###
a = torch.randn(1, 2, 3, 4, 5)
torch.numel(a)

120

In [6]:
# Example 2 - ### 先用np轉換torch的型式再用numel返回有幾個元素 ###
a = np.random.randint(low=0, high=10, size=(2,2))
b = torch.from_numpy(a)
torch.numel(b)

4

### Function 4 - torch.unsqueeze() / torch.squeeze()

In [10]:
# Example 1 - ### squeeze()： 维度壓缩，去除為1的的维度 ###
a = torch.randn(1, 2, 3, 4, 5)
b = torch.squeeze(a)
print(f'b: {type(b)}, {b.shape}')

# 帶參數：
a = torch.randn(1, 2, 3, 4, 5)
# 因第2為度不為1 -> 原樣
b = torch.squeeze(a, 2)
print(f'b: {type(b)}, {b.shape}')

b: <class 'torch.Tensor'>, torch.Size([2, 3, 4, 5])
b: <class 'torch.Tensor'>, torch.Size([1, 2, 3, 4, 5])


In [12]:
# Example 2 - ### ㄋqueeze()： 维度壓缩，去除為1的的维度 ###
a = torch.randn(1, 2, 3, 4, 5)
b = torch.squeeze(a)
print(f'b: {type(b)}, {b.shape}')

# 帶參數：
a = torch.randn(1, 2, 3, 4, 5)
# 因第2為度不為1 -> 原樣
b = torch.squeeze(a, 2)
print(f'b: {type(b)}, {b.shape}')